name: Cypress tests
on: [push]
jobs: 
  cypress-run:
    runs-on: window-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3.3.0
        - name: Cypress.io  
          uses: cypress-io/github-action@v5.0.5
          with:
            start: npm start
